name: Check example code

on: [push, pull_request]

jobs:
  test:
    name: Code Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EtherOJ/EtherTester@master
        with:
            target: '**/*.problem'
